old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    producers:
        messaging:
            class: App\Rabbit\MessagingProducer
            connection:       default
            exchange_options: { name: 'qMessages', type: direct }
            queue_options:    { name: 'qMessages'}
    consumers:
            messaging:
                connection:       default
                exchange_options: { name: 'qMessages', type: direct }
                queue_options:    { name: 'qMessages'}
                callback:         message_service
                enable_logger:    true
